default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: SQL6521

development:
  <<: *default
  database: shoutr_development

test:
  <<: *default
  database: shoutr_test

production:
  <<: *default
  database: shoutr_production
  username: shoutr
  password: <%= ENV['SHOUTR_DATABASE_PASSWORD'] %>
